blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://github.com/delitamakanda/cli-multi-agent
    about: Pour toute question ou problème, veuillez consulter la documentation du projet.